module.exports.proje = require('./proje.route')
module.exports.atama = require('./atama.route')
module.exports.oncelik = require('./oncelik.route')
module.exports.durum = require('./durum.route')
module.exports.yorum = require('./yorum.route')
module.exports.etiket = require('./etiket.route')