module.exports.projeService = require('./proje.service')
module.exports.atamaService = require('./atama.service')
module.exports.durumService = require('./durum.service')
module.exports.oncelikService = require('./oncelik.service')
module.exports.yorumService = require('./yorum.service')
module.exports.etiketService = require('./etiket.service')
module.exports.gorevService = require('./gorev.service')