module.exports.atamaValidation = require('./atama.validation')
module.exports.oncelikValidation = require('./oncelik.validation')
module.exports.durumValidation = require('./durum.validation')
module.exports.yorumValidation = require('./yorum.validation')
module.exports.etiketValidation = require('./etiket.validation')
module.exports.projeValidation = require('./proje.validation')