module.exports.projeController = require('./proje.controller')
module.exports.atamaController = require('./atama.controller')
module.exports.oncelikController = require('./oncelik.controller')
module.exports.durumController = require('./durum.controller')
module.exports.yorumController = require('./yorum.controller')
module.exports.etiketController = require('./etiket.controller')
module.exports.gorevController = require('./gorev.controller')