module.exports.Proje = require('./proje.model')
module.exports.Atama = require('./atama.model')
module.exports.Durum = require('./durum.model')
module.exports.Oncelik = require('./oncelik.model')
module.exports.Yorum = require('./yorum.model')
module.exports.Etiket = require('./etiket.model')